logging:
  config: classpath:logback/logback.xml
  level:
    cn.edu.pzhu.blog.dao: debug

spring:
  datasource:
    url: jdbc:mysql://47.107.110.158:3306/blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123qwe==GHJ
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  mvc:
    view:
      prefix: classpath:/views/
      suffix: .html


mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081


qiniu:
  accessKey: "uC91QV9e-sTqu_mNI2WsWV2B1sFmplool07xUAYa"
  secretKey: "tqaFZhdhns4mffEqlal8b_XBBq4CvdHat0p5nYwU"
  bucket: "zhangchao"
  path: "pq9hn0x7y.bkt.clouddn.com"
