logging:
  config: classpath:logback/logback.xml
  level:
    cn.edu.pzhu.blog.dao: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/views/

mybatis:
  mapper-locations: classpath:mapper/*.xml
